package com.flutterassetsgen.core

/**
 * @param identifier the generated Dart constant name, e.g. "imagesLogo"
 * @param assetPath the asset's path as referenced from Dart/pubspec.yaml, e.g. "assets/images/logo.png"
 */
data class AssetEntry(val identifier: String, val assetPath: String)

/** Result of [DartAssetsGenerator.buildEntries]: the entries plus any naming collisions that had to be resolved. */
data class BuildResult(val entries: List<AssetEntry>, val renamedDuplicates: List<String>)

/**
 * Turns scanned asset files into deterministic, uniquely-named [AssetEntry]
 * values and renders them into a complete, valid `Assets.dart` source file.
 *
 * All naming logic itself lives in [AssetNameConverter]; this class is only
 * responsible for assembling entries (including duplicate-safe naming) and
 * formatting Dart source - it does not know how to scan the filesystem or
 * how to talk to the IDE.
 */
object DartAssetsGenerator {

    /**
     * @param scannedAssets assets found under the assets root, as produced by [AssetScanner.scan]
     * @param assetsDirName the assets directory name/path as it appears in the generated asset
     *   strings, e.g. "assets" so that "images/logo.png" becomes "assets/images/logo.png"
     */
    fun buildEntries(scannedAssets: List<ScannedAsset>, assetsDirName: String): BuildResult {
        val usedNames = HashMap<String, Int>()
        val renamedDuplicates = mutableListOf<String>()
        val entries = mutableListOf<AssetEntry>()

        // scannedAssets is already sorted by relativePath, so output order is deterministic.
        for (asset in scannedAssets) {
            val baseIdentifier = AssetNameConverter.toDartIdentifier(asset.relativePath)
            val identifier = disambiguate(baseIdentifier, usedNames)
            if (identifier != baseIdentifier) {
                renamedDuplicates += "${asset.relativePath} -> $identifier (name collision with another asset)"
            }
            val assetPath = "$assetsDirName/${asset.relativePath}"
            entries += AssetEntry(identifier = identifier, assetPath = assetPath)
        }

        return BuildResult(entries = entries, renamedDuplicates = renamedDuplicates)
    }

    private fun disambiguate(baseIdentifier: String, usedNames: MutableMap<String, Int>): String {
        val seenCount = usedNames[baseIdentifier]
        if (seenCount == null) {
            usedNames[baseIdentifier] = 1
            return baseIdentifier
        }
        var attempt = seenCount + 1
        var candidate = "$baseIdentifier${attempt}"
        while (usedNames.containsKey(candidate)) {
            attempt += 1
            candidate = "$baseIdentifier${attempt}"
        }
        usedNames[baseIdentifier] = attempt
        usedNames[candidate] = 1
        return candidate
    }

    /** Renders the final `Assets.dart` source text for the given [className] and [entries]. */
    fun renderDartFile(className: String, entries: List<AssetEntry>): String {
        val sb = StringBuilder()
        sb.appendLine("// GENERATED CODE - DO NOT MODIFY BY HAND")
        sb.appendLine("// Generated by FlutterAssetsGenerator - press Alt+G to regenerate.")
        sb.appendLine()
        sb.appendLine("// ignore_for_file: type=lint")
        sb.appendLine()
        sb.appendLine("class $className {")
        sb.appendLine("  $className._();")

        if (entries.isNotEmpty()) {
            sb.appendLine()
            for (entry in entries) {
                sb.appendLine("  static const String ${entry.identifier} = '${escapeDartString(entry.assetPath)}';")
            }
        }

        sb.appendLine("}")
        sb.appendLine()
        return sb.toString()
    }

    private fun escapeDartString(value: String): String =
        value.replace("\\", "\\\\").replace("'", "\\'").replace("$", "\\$")
}
